# Generated by Django 5.0.2 on 2024-02-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_picture',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/thumbnails/001/623/833/original/movie-trailer-coming-soon-background-video.jpg', max_length=1000),
        ),
    ]
