# Generated by Django 5.0.2 on 2024-03-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0002_alter_movie_trailer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='visibility',
            field=models.CharField(blank=True, default='Now Playing!.....', max_length=100),
        ),
    ]
