# Generated by Django 5.0.2 on 2024-03-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0003_movie_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='visibility',
            field=models.CharField(blank=True, default='Now Playing', max_length=100),
        ),
    ]
